kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: message
  image: busybox
  commands:
  - echo "Hello World"

- name: test
  image: node
  commands:
  - npm install
  - npm test
